[package]
name = "custom_derive"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
erc20 = { path = "../erc20" }
erc20_derive = { path = "../erc20/erc20_derive" }
function_name = "0.2.0"
